guard :shell do
  watch(/Appendices\/.*\.tex/) { `pdflatex Thesis.tex`}
  watch(/Chapters\/.*\.tex/) { `pdflatex Thesis.tex` }
  watch(/Thesis\.tex/) { `pdflatex Thesis.tex` }
  watch(/Thesis\.cls/) { `pdflatex Thesis.tex` }
end
